### ISSUE TITLE
warning message is displayed

### ISSUE THREAD

**Issue by Suzuk1** [paprikachan/scSVAS#1]
Hi

Thank you for developing a user-friendly tool. I want to try to use the scSVAS website(https://sc.deepomics.org), but the security warning message is displayed; I tried in Chrome, Firefox and Safari. So, Could you tell me any idea to connect the scSVAS website safely?

<img width="890" alt="Screenshot 2021-06-23 at 15 53 25" src="https://user-images.githubusercontent.com/19612536/123050384-9b624600-d43b-11eb-8e29-1af36bd7fd58.png">

**Comment by thelingxichen** [comment]
Hi @Suzuk1 , thanks for trying scSVAS.  Now there is a problem with the security certificate of the website. Hopefully, we will solve it at next week. Now to try the website, please click the "Advanced" button, and click "Proceed to sc.deepomics.org (unsafe)".

**Comment by Suzuk1** [comment]
I understood the situation and wait for a safe connection. I hope that the security certificate problem will be solved soon!
