### ISSUE TITLE
how to prepare _evo.json file from 10x data ?

### ISSUE THREAD

**Issue by Suzuk1** [paprikachan/scSVAS#2]
Hi, thank you for the recovery of the security certification! 

I have two questions concerning about making a `*_evo.json` file.
I want to use “Clonal Linage” visualization application using 10x data(h5 file). For “Clonal Linage”, I need to prepare` *_evo.json` by running scSVAS scripts with `*_cnv.csv`, `*_meta.csv`, and targeted gene list.
 
① I checked the git scSVAS repository and found some scripts in scSVAS/script. 
・Running cSVAS/script/process_10x_h5.py will make a  `_cnv.csv` file.
・Which script makes a `*_meta.csv` file from a 10x h5 file?
・Which script makes a` *_evo.json` file?
 
② I tried running `$ process_10x_h5.py -h` after `$pip install biotool`, but the error message; `ImportError: cannot import name 'genome' from 'biotool' (unknown location)` is displayed. 
I checked;
```
>> import biotool
>>> biotool.genome
Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
AttributeError: module 'biotool' has no attribute 'genome'
```
Could you tell me your advice for this error message?

Thank you very much for valuable scSVAS !

**Comment by thelingxichen** [comment]
Hi @Suzuk1 ,

Really sorry for the inconvenience caused.
I will upload a version of the detailed operation manual for "Clonal Lineage".
Please stay tuned for the updates.
BTW, you can send me your 10x data (h5 file) if it's convenient so that I can test on that file.

Best,
Lingxi.

**Comment by Suzuk1** [comment]
Hi Lingxi,

All right, I am looking forward to the detailed operation manual!
I appreciate your proposal, but I want to try to use scSVAS by myself. So, I wait for the update.

Kind regards,
