### ISSUE TITLE
how to +Add project in scSVAS site?

### ISSUE THREAD

**Issue by Suzuk1** [paprikachan/scSVAS#3]
Hi,
I usually use the [scSVAS site](https://sc.deepomics.org/demo-project) and want to use “+Add project” button, however “+Add project” button is not responding.So it is appreciated if you could tell me how to use “+Add project”.

**Comment by thelingxichen** [comment]
Hi @Suzuk1 ,
 
Really sorry the "+Add project" functionality is not available. 
Please just try the "Demo Project", it contains all functionalities.

Best,
Lingxi

**Comment by Suzuk1** [comment]
Hi Lingxi,

I got it, and I use “Demo project.”
Thank you for the answer to my question :)
